name: Node.js CI

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Installera dependencies
      - name: Install dependencies
        run: npm ci

      # 2. Formattera, linta och bygga
      - name: Run Prettier
        run: npm run format --if-present

      - name: Run ESLint
        run: |
          npm run lint
          npm run lint:fix

      # 3. Genererar Prisma Client
      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Build project
        run: npm run build

      # 4. Kör tester
      - name: Run tests
        run: npm test -- --detectOpenHandles

      # 5. Databas migrering
      - name: Run database migrations
        run: npx prisma migrate deploy